export default {
  color: {
    darkGreen: '#17453F',
    green: '#28786D',
    lightGreen: '#68C4B8',
    black: '#1C1C1C',
    grey: '#F5F5F5',
    line: '#E5E5E5',
  },
  font: {
    phone: {
      h1: '8rem',
      h1Medium: '7.2rem',
      h2: '3.2rem',
      h3: '4.8rem',
      h4: '2.4rem',
      h5: '3.2rem',
      p: '1.6rem',
      meta: '1.2rem',
    },
    desktop: {
      h1: '10.4rem',
      h2: '4rem',
      h3: '8rem',
      h4: '3.6rem',
      h5: '2.4rem',
      h6: '1.6rem',
      p: '1.6rem',
      meta: '1.2rem',
    },
  },
  letterSpacing: {
    p: '0.05rem',
  },
  lineHeight: {
    phone: {
      h1: '8.8rem',
      h1Medium: '8rem',
      h2: '4rem',
      h3: '5.6rem',
      h4: '2.4rem',
      h5: '5.6rem',
      p: '2.4rem',
      meta: '2rem',
    },
    desktop: {
      h1: '11.2rem',
      h2: '4.8rem',
      h3: '8.8rem',
      h4: '4rem',
      h5: '3.2rem',
      h6: '2.4rem',
      p: '2.4rem',
      meta: '2rem',
    },
  },
  transition: {
    nav: 'all 0.3s ease-in-out',
    link: 'all 0.2s ease-in-out',
    buttons: 'all 0.5s ease-in',
    images: 'all .2s ease-in-out',
    scrollAppear: 'all .2s ease-in-out',
    scrollDisappear: 'all .1s ease-out',
  },
  margin: {
    desktop: {
      top: '1.6rem',
      bottom: '3.2rem',
    },
  },
  borderRadius: '1.6rem',
  breakPoint: {
    desktopSmall: '1024px',
    tablet: '768px',
    phoneLarge: '426px',
    phoneMedium: '376px',
    phoneSmall: '321px',
  },
}
